all:

deploy-doc: target/doc/.git/config
	cargo doc
	echo '<meta http-equiv="refresh" content="0;url='`cargo metadata --format-version 1 | python -c 'import json, sys; print(json.load(sys.stdin)["resolve"]["root"].split()[0])'`'/index.html"/>' >target/doc/index.html
	cd target/doc \
	&& git add -A \
	&& git commit --amend -q -m Autogenerated \
	&& git push -f origin master:gh-pages \

target/doc/.git/config:
	mkdir -p target/doc
	url=`git remote -v | grep origin | awk '{ printf "%s", $$2; exit }'` \
	&& cd target/doc \
	&& git init \
	&& git config user.name Bot \
	&& git config user.email "<>" \
	&& git commit -m _ --allow-empty \
	&& git remote add origin $$url

.PHONY: all
